# Generated by Django 5.2.15 on 2026-06-23 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("interval", models.CharField(max_length=10)),
                ("price_cents", models.IntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("stripe_price_id", models.CharField(blank=True, max_length=120)),
                ("apple_product_id", models.CharField(blank=True, max_length=120)),
                ("google_product_id", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("past_due", "past_due"),
                            ("canceled", "canceled"),
                            ("expired", "expired"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stripe", "stripe"),
                            ("apple", "apple"),
                            ("google", "google"),
                        ],
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "current_period_end"],
                        name="subscriptio_user_id_abb34c_idx",
                    )
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
