# Generated by Django 5.2.15 on 2026-06-27 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_episode_status_alter_show_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("row", "row"), ("hero", "hero")],
                        default="row",
                        max_length=8,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.collection",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="catalog.show",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("collection", "show")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="shows",
            field=models.ManyToManyField(
                related_name="collections",
                through="catalog.CollectionItem",
                to="catalog.show",
            ),
        ),
    ]
