# Generated by Django 5.2.15 on 2026-06-29 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_collection_collectionitem_collection_shows"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=12)),
                ("label", models.CharField(blank=True, max_length=60)),
                ("ready", models.BooleanField(default=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="catalog.video",
                    ),
                ),
            ],
            options={
                "ordering": ["language"],
                "unique_together": {("video", "language")},
            },
        ),
    ]
