# Generated by Django 5.2.15 on 2026-06-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_creator",
            field=models.BooleanField(default=False),
        ),
    ]
