# Generated by Django 5.2.15 on 2026-06-23 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_account_id", models.CharField(blank=True, max_length=120)),
                ("details_submitted", models.BooleanField(default=False)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("revenue_pool_cents", models.BigIntegerField(default=0)),
                ("platform_fee_bps", models.IntegerField(default=3000)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("computed", "computed"),
                            ("paid_out", "paid_out"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["status", "period_start"],
                        name="payouts_pay_status_008cd7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatorEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("watched_seconds", models.BigIntegerField(default=0)),
                ("share_bps", models.IntegerField(default=0)),
                ("gross_cents", models.BigIntegerField(default=0)),
                ("fee_cents", models.BigIntegerField(default=0)),
                ("net_cents", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                            ("skipped", "skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("stripe_transfer_id", models.CharField(blank=True, max_length=120)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="payouts.payoutperiod",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["period", "status"],
                        name="payouts_cre_period__f2b92a_idx",
                    )
                ],
                "unique_together": {("period", "creator")},
            },
        ),
    ]
